site_name: 马克思主义文库
theme:
  name: material
  language: zh
  palette:
    - scheme: default
      primary: red
      toggle:
        icon: material/brightness-7
        name: 切换到夜间模式
    - scheme: slate
      primary: red
      toggle:
        icon: material/brightness-4
        name: 切换到日间模式
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.follow
    - toc.integrate
nav:
  - 主页: /
  - 索引:
    - /index/
    - 作者: /index/authors.md
  - 政治经济学概论:
    - /articles/xuhe/political-economy/
    - 第一节 商品是资本主义经济的细胞: chap-01/sec-01.md
extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: 中文
      link: /zh/
      lang: zh
plugins:
  - tags:
      tags_file: index/authors.md