site_name: 马克思主义文库
theme:
  name: material
  language: zh
  font:
    text: Noto Serif SC
  palette:
    - scheme: default
      primary: red
      toggle:
        icon: material/brightness-7
        name: 切换到夜间模式
    - scheme: slate
      primary: red
      toggle:
        icon: material/brightness-4
        name: 切换到日间模式
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.follow
nav:
  - 主页: index.md
  - 索引:
    - index/index.md
    - 按作者索引: index/authors.md
  - 政治经济学概论:
    - articles/xuhe/political-economy/index.md
    - 第一章 商品和货币:
      - 第一节 商品是资本主义经济的细胞: articles/xuhe/political-economy/chap-01/sec-01.md
extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: 中文
      link: /zh/
      lang: zh
plugins:
  - tags:
      tags_file: index/authors.md