site_name: 马克思主义文库

theme:
  name: material
  language: zh
  # font:
  #   text: Noto Serif SC
  palette:
    - scheme: default
      primary: red
      toggle:
        icon: material/brightness-7
        name: 切换到夜间模式
    - scheme: slate
      primary: red
      toggle:
        icon: material/brightness-4
        name: 切换到日间模式
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.follow

nav:
  - 主页: index.md
  - 索引:
    - index/index.md
    - 按作者索引: index/authors.md
  - 政治经济学概论:
    - articles/xuhe/political-economy/index.md
    - 第一章 商品和货币:
      - articles/xuhe/political-economy/chap-01/index.md
      - 第一节 商品与资本主义经济: articles/xuhe/political-economy/chap-01/sec-01.md
      - 第二节 商品的使用价值和价值: articles/xuhe/political-economy/chap-01/sec-02.md
      - 第三节 劳动的二重性: articles/xuhe/political-economy/chap-01/sec-03.md
      - 第四节 价值形态与货币: articles/xuhe/political-economy/chap-01/sec-04.md
      - 第五节 货币的职能: articles/xuhe/political-economy/chap-01/sec-05.md
      - 第六节 价值规律: articles/xuhe/political-economy/chap-01/sec-06.md
      - 第七节 商品拜物教: articles/xuhe/political-economy/chap-01/sec-07.md
      - 第八节 对资产阶级理论的批判: articles/xuhe/political-economy/chap-01/sec-08.md
    - 第二章 资本和剩余价值:
      - articles/xuhe/political-economy/chap-02/index.md
      - 第一节 由货币到资本的转化: articles/xuhe/political-economy/chap-02/sec-01.md
      - 第二节 劳动和价值增殖过程: articles/xuhe/political-economy/chap-02/sec-02.md
      - 第三节 不变资本和可变资本: articles/xuhe/political-economy/chap-02/sec-03.md
      - 第四节 绝对剩余价值的生产: articles/xuhe/political-economy/chap-02/sec-04.md
      - 第五节 相对剩余价值的生产: articles/xuhe/political-economy/chap-02/sec-05.md
      - 第六节 相对剩余价值三阶段: articles/xuhe/political-economy/chap-02/sec-06.md
    - 第三章 工资:
      - articles/xuhe/political-economy/chap-03/index.md
      - 第一节 工资的实质: articles/xuhe/political-economy/chap-03/sec-01.md
      - 第二节 工资形式: articles/xuhe/political-economy/chap-03/sec-02.md
      - 第三节 相对工资和下降趋势: articles/xuhe/political-economy/chap-03/sec-03.md
      - 第四节 无产者争取工资的斗争: articles/xuhe/political-economy/chap-03/sec-04.md

plugins:
  - tags:
      tags_file: index/authors.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - md_in_html

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  - src/css/custom.css

extra_javascript:
  - src/javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  - src/javascripts/custom.js