site_name: 马克思主义文库

theme:
  name: material
  language: zh
  # font:
  #   text: Noto Serif SC
  palette:
    - scheme: default
      primary: red
      toggle:
        icon: material/brightness-7
        name: 切换到夜间模式
    - scheme: slate
      primary: red
      toggle:
        icon: material/brightness-4
        name: 切换到日间模式
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit
    - content.action.view
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye

repo_url: https://github.com/Marxism-Doc/Marxism-Doc.github.io
repo_name: Marxism-Doc
edit_uri: edit/main/docs/

nav:
  - 主页: index.md
  - 索引:
    - index/index.md
    - 按作者索引: index/authors.md
  - 政治经济学概论:
    - articles/xuhe/political-economy/index.md
    - 一　商品和货币:
      - articles/xuhe/political-economy/chap-01/index.md
      - 1　商品与资本主义经济: articles/xuhe/political-economy/chap-01/sec-01.md
      - 2　商品的使用价值和价值: articles/xuhe/political-economy/chap-01/sec-02.md
      - 3　劳动的二重性: articles/xuhe/political-economy/chap-01/sec-03.md
      - 4　价值形态与货币起源: articles/xuhe/political-economy/chap-01/sec-04.md
      - 5　货币的职能: articles/xuhe/political-economy/chap-01/sec-05.md
      - 6　价值规律: articles/xuhe/political-economy/chap-01/sec-06.md
      - 7　商品拜物教: articles/xuhe/political-economy/chap-01/sec-07.md
      - 8　对资产阶级理论的批判: articles/xuhe/political-economy/chap-01/sec-08.md
    - 二　资本和剩余价值:
      - articles/xuhe/political-economy/chap-02/index.md
      - 1　由货币到资本的转化: articles/xuhe/political-economy/chap-02/sec-01.md
      - 2　劳动过程和价值增殖过程: articles/xuhe/political-economy/chap-02/sec-02.md
      - 3　不变资本和可变资本: articles/xuhe/political-economy/chap-02/sec-03.md
      - 4　绝对剩余价值的生产: articles/xuhe/political-economy/chap-02/sec-04.md
      - 5　相对剩余价值的生产: articles/xuhe/political-economy/chap-02/sec-05.md
      - 6　相对剩余价值的发展阶段: articles/xuhe/political-economy/chap-02/sec-06.md
    - 三　工资:
      - articles/xuhe/political-economy/chap-03/index.md
      - 1　工资的实质: articles/xuhe/political-economy/chap-03/sec-01.md
      - 2　工资形式: articles/xuhe/political-economy/chap-03/sec-02.md
      - 3　相对工资和实际工资降势: articles/xuhe/political-economy/chap-03/sec-03.md
      - 4　无产阶级争取工资的斗争: articles/xuhe/political-economy/chap-03/sec-04.md
    - 四　资本积累及其历史趋势:
      - articles/xuhe/political-economy/chap-04/index.md
      - 1　简单和扩大再生产: articles/xuhe/political-economy/chap-04/sec-01.md
      - 2　资本有机构成、积聚和集中: articles/xuhe/political-economy/chap-04/sec-02.md
      - 3　资本积累的过程和失业: articles/xuhe/political-economy/chap-04/sec-03.md
      - 4　对马尔萨斯人口理论的批判: articles/xuhe/political-economy/chap-04/sec-04.md
      - 5　无产阶级的贫困化: articles/xuhe/political-economy/chap-04/sec-05.md
      - 6　资本主义积累的历史趋势: articles/xuhe/political-economy/chap-04/sec-06.md
    - 五　资本的循环和周转:
      - articles/xuhe/political-economy/chap-05/index.md
      - 1　产业资本循环的三个阶段: articles/xuhe/political-economy/chap-05/sec-01.md
      - 2　产业资本循环的三种形态: articles/xuhe/political-economy/chap-05/sec-02.md
      - 3　流通时间和流通费用: articles/xuhe/political-economy/chap-05/sec-03.md
      - 4　资本的周转时间和周转次数: articles/xuhe/political-economy/chap-05/sec-04.md
      - 5　固定资本和流动资本: articles/xuhe/political-economy/chap-05/sec-05.md
      - 6　垫付资本的总周转及其周期: articles/xuhe/political-economy/chap-05/sec-06.md
      - 7　劳动期间和生产、流通时间: articles/xuhe/political-economy/chap-05/sec-07.md
      - 8　可变资本的周转及其影响: articles/xuhe/political-economy/chap-05/sec-08.md
    - 六　社会资本的再生产和流通:
      - articles/xuhe/political-economy/chap-06/index.md
      - 1　个别资本和社会资本: articles/xuhe/political-economy/chap-06/sec-01.md
      - 2　简单再生产社会产品的实现: articles/xuhe/political-economy/chap-06/sec-02.md
      - 3　扩大再生产社会产品的实现: articles/xuhe/political-economy/chap-06/sec-03.md
      - 4　社会产品实现的矛盾和困难: articles/xuhe/political-economy/chap-06/sec-04.md
    - 七　平均利润和生产价格:
      - articles/xuhe/political-economy/chap-07/index.md
      - 1　生产成本和利润、利润本质: articles/xuhe/political-economy/chap-07/sec-01.md
      - 2　利润率和影响利润率的因素: articles/xuhe/political-economy/chap-07/sec-02.md
      - 3　利润转化为平均利润: articles/xuhe/political-economy/chap-07/sec-03.md
      - 4　价值转化为生产价格: articles/xuhe/political-economy/chap-07/sec-04.md
      - 5　平均利润率下降趋势的规律: articles/xuhe/political-economy/chap-07/sec-05.md
    - 八　商业资本和商业利润:
      - articles/xuhe/political-economy/chap-08/index.md
      - 1　商业利润从产业资本中独立: articles/xuhe/political-economy/chap-08/sec-01.md
      - 2　商业利润和商业价格: articles/xuhe/political-economy/chap-08/sec-02.md
      - 3　商业纯粹流通费用及其补偿: articles/xuhe/political-economy/chap-08/sec-03.md
      - 4　资本主义商业的形式: articles/xuhe/political-economy/chap-08/sec-04.md
      - 5　资本主义国家的对外贸易: articles/xuhe/political-economy/chap-08/sec-05.md
    - 九　借贷资本和信用:
      - articles/xuhe/political-economy/chap-09/index.md
      - 1　借贷资本的本质和特点: articles/xuhe/political-economy/chap-09/sec-01.md
      - 2　利息和企业利润: articles/xuhe/political-economy/chap-09/sec-02.md
      - 3　商业信用和银行信用: articles/xuhe/political-economy/chap-09/sec-03.md
      - 4　股份公司和虚拟资本: articles/xuhe/political-economy/chap-09/sec-04.md
      - 5　信用在资本主义经济中作用: articles/xuhe/political-economy/chap-09/sec-05.md
      - 6　信用制度下的货币流通: articles/xuhe/political-economy/chap-09/sec-06.md

plugins:
  - tags:
      tags_file: index/authors.md
  - search:
      lang: zh

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  - src/css/custom.css

extra_javascript:
  - src/javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  - src/javascripts/custom.js